# Generated by Django 5.0.4 on 2024-04-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('total_number', models.IntegerField(verbose_name='total_nuber')),
                ('buy_now', models.IntegerField(verbose_name='vuy_now')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='end_date')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16, verbose_name='category')),
                ('marka', models.CharField(max_length=16, verbose_name='marka')),
                ('model', models.CharField(max_length=16, verbose_name='model')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('year', models.SmallIntegerField(default=2020, verbose_name='year')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='mileage')),
                ('city', models.CharField(max_length=16, verbose_name='city')),
                ('country', models.CharField(max_length=16, verbose_name='country')),
                ('with_photo', models.BooleanField(default=True, verbose_name='with_photo')),
                ('color', models.CharField(max_length=16, verbose_name='color')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='volume')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
