# Generated by Django 5.0.4 on 2024-04-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category_en',
            field=models.CharField(max_length=16, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='car',
            name='category_kg',
            field=models.CharField(max_length=16, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='car',
            name='category_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_en',
            field=models.CharField(max_length=16, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_kg',
            field=models.CharField(max_length=16, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_en',
            field=models.CharField(max_length=16, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_kg',
            field=models.CharField(max_length=16, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_en',
            field=models.CharField(max_length=16, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_kg',
            field=models.CharField(max_length=16, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_kg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka_en',
            field=models.CharField(max_length=16, null=True, verbose_name='marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka_kg',
            field=models.CharField(max_length=16, null=True, verbose_name='marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_en',
            field=models.CharField(max_length=16, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_kg',
            field=models.CharField(max_length=16, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='model'),
        ),
    ]
