# Generated by Django 5.0.4 on 2024-04-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_car_category_en_car_category_kg_car_category_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='category_kg',
            new_name='category_ky',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='city_kg',
            new_name='city_ky',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='color_kg',
            new_name='color_ky',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='country_kg',
            new_name='country_ky',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='marka_kg',
            new_name='marka_ky',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model_kg',
            new_name='model_ky',
        ),
    ]
